// Write the figure down: `npm run figure:dump`.
//
// The engine is the source of truth for what the body is -- where its bones
// rest and how thick it is along every chain -- and this hands that over to
// `bake.py`, which is Python and cannot import TypeScript. The JSON is
// committed so that baking needs this step only when the figure changes.
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { MeshStandardNodeMaterial } from 'three/webgpu';
import { it } from 'vitest';
import { createProceduralHuman } from '../../src/engine/avatar/ProceduralHuman';
import { OUTFIT } from '../../src/engine/avatar/Outfit';

it('writes the figure out', () => {
  // The material is never used: nothing here draws. The figure needs one to
  // exist, so it gets the cheapest one that is not the world's.
  const human = createProceduralHuman(() => new MeshStandardNodeMaterial());
  const description = human.describe();
  const out = join(dirname(fileURLToPath(import.meta.url)), 'figure.json');
  writeFileSync(
    out,
    JSON.stringify(
      {
        note: 'Generated by `npm run figure:dump` from src/engine/avatar. Do not edit by hand.',
        eye: [human.eye.x, human.eye.y, human.eye.z],
        outfit: OUTFIT,
        ...description,
      },
      null,
      1,
    ),
  );
  human.dispose();
  console.log(`figure.json: ${description.bones.length} bones, ${description.chains.length} chains`);
});
